### ISSUE TITLE
function roadmap for version 1.0

### ISSUE THREAD

**Issue by Alcampopiano** [Alcampopiano/hypothesize#1]
A small subset of Wilcox's functions that should be included in the first major release.

### utilities
- [x] `con1way` and `con2way` for creating linear contrasts

### two independent groups
- [x] `yuenbt` bootstrapped-t CI for ut1 - ut2
- [x] `pb2gen` percentile bootstrap CI for difference between any estimators

### two dependent groups
- [x] `ydbt` bootstrapped-t CI for ut1 - ut2 
- [x] `bootdpci` percentile bootstrap method any estimator; can set options for using difference scores or measures of location based on the marginal distributions
- [x] `loc2dif` and `l2drmci` difference between estimators using all combinations of difference scores and percentile bootstrap, respectively 

### one-way methods based on multiple comparisons for independent groups
- [x] `linconb` test linear contrasts using bootstrap-t method
- [x] `tmcppb` rom/hoch/ben-type methods using percentile bootstrap and trimmed means

### one-way methods based on multiple comparisons for dependent groups
- [x] `rmmcppb` multiple comparisons for J dependent groups using percentile boot method
- [x] `lindepbt` bootstrap-t method for multiple comparisons among J dependent groups

### within-within designs
- [x] `wwmcppb` multiple comparisons for main effects and interactions with linear contrasts using percentile boot
- [x] `wwmcpbt` multiple comparisons for main effects and interactions with linear contrasts using bootstrap-t

### mixed designs
- [x] `bwmcp` (`bwamcp`, `bwbmcp`, `bwimcp`) all main effects and interactions using bootstrap-t
- [x] `spmcpa`, `spmcpb`, `spmcpi` like the above functions but using the percentile boot
- [x] `bwmcppb` (only for trimmed means?) all main effects and interactions with percentile boot

### correlations
- [x] `pbcor` percentage bend correlation
- [x] `pball` percentage bend correlation for a set of variables
- [x] `wincor` winsorized correlation
- [x] `winall` winsorized correlation for a set of variables
- [x] `corb` test for zero correlation using bootstrapping
